javascript/lib/api/src/auth/auth-provider.ts
This is a bugfix that arises with URL encoding of extra query params provided by the user for the authentication step. Encoding the params automatically causes trouble like encoded '=' signs which will then be not readable by REST controllers
=> [JS] Bugfix URL encoding

javascript/Jenkinsfile
Instead of providing release functionality, the Jenkinsfile should rather provide functionality to build feature branches. The release functionality is moved to the Eclipse Ditto build infrastructure as it is irrelevant for users.
=> Let Jenkinsfile build feature branches

java/src/main/java/org/eclipse/ditto/client/internal/bus/DefaultRegistry.java
=> got rid of caching "not found" selectors in the cache which caused a memory leak

javascript/lib/api/package.json, javascript/lib/dom/package.json, javascript/lib/node/package.json
The scoped packages need a special configuration to make them publishable via lerna (see https://github.com/lerna/lerna/tree/master/commands/publish#publishconfigaccess).
Signed-off-by: Florian Fendt <Florian.Fendt@bosch-si.com>
=> Make scoped js packages publishable

.gitignore, java/README.md, java/pom.xml
in order to get released pom in a working state with resolved version/revision placeholders
Milestone 1.0.0-M2 did contain non resolved `${revision}` placeholder which results in non-resolvable transitive Ditto dependencies.
This fixes that for the upcoming M3 release.
=> added flatten-maven-plugin and configured it to flatten the pom

java/src/main/java/org/eclipse/ditto/client/configuration/ClientCredentialsAuthenticationConfiguration.java
Added javadoc to clarify that client secrets are never sent to a Ditto backend.
=> Improved javadoc of client credentials authentication configuration

java/pom.xml, java/src/main/java/org/eclipse/ditto/client/internal/DefaultDittoClient.java, java/src/main/java/org/eclipse/ditto/client/internal/OutgoingMessageFactory.java, java/src/main/java/org/eclipse/ditto/client/live/events/EventFactory.java, java/src/main/java/org/eclipse/ditto/client/live/events/internal/ImmutableFeatureEventFactory.java, java/src/main/java/org/eclipse/ditto/client/live/events/internal/ImmutableGlobalEventFactory.java, java/src/main/java/org/eclipse/ditto/client/live/events/internal/ImmutableThingEventFactory.java, java/src/main/java/org/eclipse/ditto/client/live/internal/LiveFeatureHandleImpl.java, java/src/main/java/org/eclipse/ditto/client/live/internal/LiveImpl.java, java/src/main/java/org/eclipse/ditto/client/live/internal/LiveThingHandleImpl.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/live/events/internal/ImmutableFeatureEventFactoryTest.java, java/src/test/java/org/eclipse/ditto/client/live/events/internal/ImmutableGlobalEventFactoryTest.java, java/src/test/java/org/eclipse/ditto/client/live/events/internal/ImmutableThingEventFactoryTest.java
These are the necessary adjustments to Ditto Java client for PR https://github.com/eclipse/ditto/pull/557
The `DittoHeader` `"source"` was removed there which was still used in the client (but only for logging), so the usage of this header was also removed.
=> Response header mapping adjustments for Ditto PR

java/src/main/java/org/eclipse/ditto/client/live/messages/internal/ImmutableMessageSender.java
Otherwise the header is not present at all which is interpreted by Ditto as required. See https://github.com/eclipse/ditto/issues/616
=> Set response-required to false if no response consumer is specified

java/README.md, java/src/main/java/org/eclipse/ditto/client/messaging/AuthenticationException.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java
Fixes unnecessary boxing of AuthenticationException objects in the WebSocketMessagingProvider. 
The AuthenticationException containing the correct failure reason was only to be found at the bottom of the stack trace.
With this PR, the correct exception will stay on top of the stack trace and additionally if we know the failure code, this will be printed in the exceptions message.
=> Throw correct failure of AuthenticationException

javascript/lib/api/README.md, javascript/lib/api/src/client/handles/messages-http.ts, javascript/lib/api/src/client/handles/things.ts, javascript/lib/api/src/options/request.options.ts, javascript/lib/api/tests/client/http/things.http.spec.ts, javascript/lib/api/tests/client/websocket/things.websocket.spec.ts, javascript/lib/api/tests/options/request.options.spec.ts
With the current interface, it is not possible to set all options supported by the API. The most prominent example is that you can only use LIMIT/OFFSET pagination for the search endpoint, while cursor-based pagination is advised by the API itself.
To make it easier to extend these options, this MR adds base interfaces for the `*Options` classes, renaming the existing classes to `Default*Options` (as opted by @ffendt ).
At Aloxy, we're also creating an SSE extension on top of this SDK, and we'd like to reuse these options as much as possible.
=> Create interfaces for options

java/src/main/java/org/eclipse/ditto/client/live/messages/internal/ImmutableMessageSender.java
Don't force response-required to be false when calling send() without response consumer.
=> Allow to respond to live messages via ditto client

java/src/main/java/org/eclipse/ditto/client/messaging/MessagingException.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/Retry.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/RetryTest.java
Note that I also added a ping timer for the websocket connection which allows us to be notified when there is a network interruption.
Without this ping, no reconnect would be triggered.
=> Rework reconnect behaviour of java client

java/pom.xml
Dependency to "org.reactivestreams" was introduced in Ditto Java Client 1.1.0, however the OSGi import was missing.
=> fixed missing OSGi import for "org.reactivestreams"

java/src/main/java/org/eclipse/ditto/client/configuration/MessagingConfiguration.java, java/src/main/java/org/eclipse/ditto/client/configuration/WebSocketMessagingConfiguration.java, java/src/main/java/org/eclipse/ditto/client/messaging/MessagingProvider.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/Retry.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/RetryTest.java
* This way a application can have a look at errors that happen
during endless reconnecting and may decide on their own, to
shut down the client or do something different to solve the errors.
=> Add option to get notified for connection errors

java/src/main/java/org/eclipse/ditto/client/internal/DefaultDittoClient.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/DefaultPointerBus.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/Retry.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/RetryTest.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProviderTest.java
- Fix some redundant executor creation and racing.
- Do not reconnect after encountering an unrecoverable error. Unrecoverable errors are UnknownHostException and 4xx status codes from server.
- If WebsocketMessagingProvider is closed by another thread during client creation, then the client creation will throw an exception. In contrast, the previous behavior would block the calling thread forever.
Related: #65
=> Fix WebSocketMessagingProvider blocking forever on initialization when configured with an incorrect endpoint

java/src/test/java/org/eclipse/ditto/client/DittoClientLiveTest.java
which assumed that "live-response" is issued as requested-acknowledgement
=> fixed DittoClientLiveTest

java/src/main/java/org/eclipse/ditto/client/configuration/MessagingConfiguration.java, java/src/main/java/org/eclipse/ditto/client/configuration/WebSocketMessagingConfiguration.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/MockMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProviderTest.java
This allows to configure the client to do retries when initially connecting and changes the default behavior for connection initialization to don't use retries.
Signed-off-by: David Schwilk <david.schwilk@bosch.io>
=> Add possibility to enable/disable inital connection retries

java/src/main/java/org/eclipse/ditto/client/DisconnectedDittoClient.java, java/src/main/java/org/eclipse/ditto/client/DittoClients.java, java/src/main/java/org/eclipse/ditto/client/internal/DefaultDittoClient.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/AdaptableBus.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/DefaultAdaptableBus.java, java/src/main/java/org/eclipse/ditto/client/messaging/MessagingProvider.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/Retry.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/DittoClientUsageExamples.java, java/src/test/java/org/eclipse/ditto/client/internal/ClientShutdownTest.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/MockMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/RetryTest.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProviderTest.java
Until now the MessagingProvider was closed when the client was destroyed. The executor of the MessagingProvider's AdaptableBus was left open and caused blocked threads after destruction of the client.
This fixes this behavior by closing the AdaptableBus executor when closing the MessagingProvider.
Signed-off-by: David Schwilk <david.schwilk@bosch.io>
Fixes #87
=> Issue #87: Prevent leakage of AdaptableBus threads after closing the client

java/src/test/java/org/eclipse/ditto/client/DittoClientLiveTest.java
Live responses are now only considered to be a failed acknowledgements if they timed out.
=> fix unit test for live message negative acknowledgement

java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java
Do not run `WebSocketMessagingProvider.onTextMessage` and `.onBinaryMessage`
on the callback executor. Run them in the reader thread directly.
The adaptable bus already checks whether a message requires a single-
threaded executor or can be handled in a thread pool.
=> Fix reordering of messages

java/src/main/java/org/eclipse/ditto/client/internal/bus/SelectorUtil.java
This fixes a bug that caused ignoring features in a FeatureChange for change-registrations on single features, when only a single subpath exists in the feature. (i.e. feature with only properties)
This fixes the issue by including all sub-paths of features in the FeatureChange to the pointer hierarchy, which is used to distribute changes to different registrations.
Signed-off-by: David Schwilk <david.schwilk@bosch.io>
=> Fix FeatureChange consumation for specific feature change-registration

javascript/lib/api/src/client/handles/features.ts, javascript/lib/api/src/client/handles/policies.ts, javascript/lib/api/src/client/handles/things.ts, javascript/lib/api/src/model/model.ts, javascript/lib/api/src/model/policies.model.ts, javascript/lib/api/src/model/response.ts, javascript/lib/api/src/model/things.model.ts, javascript/lib/api/tests/client/http/features.http.spec.ts, javascript/lib/api/tests/client/http/policies.http.spec.ts, javascript/lib/api/tests/client/http/things.http.spec.ts, javascript/lib/api/tests/client/test.helper.ts, javascript/lib/api/tests/client/websocket/commands.websocket.spec.ts, javascript/lib/api/tests/client/websocket/events.websocket.spec.ts, javascript/lib/api/tests/client/websocket/features.websocket.spec.ts, javascript/lib/api/tests/model/policies.model.spec.ts, javascript/lib/api/tests/model/things.model.spec.ts
Refactor model structure to avoid "duplicated paths" like `features.features` for all Entities inheriting form `IndexedEntityModel` and simplify type generics.
Classes where duplicated pahts were removed:
- `Features` 
- `Acl`
- `Entries`
- `Subjects`
- `Resources`
Fixes #114
=> Refactor model structure

java/src/main/java/org/eclipse/ditto/client/live/internal/LiveImpl.java, java/src/main/java/org/eclipse/ditto/client/live/messages/internal/ImmutableMessageSender.java, java/src/test/java/org/eclipse/ditto/client/DittoClientLiveTest.java
* live-response acknowledgement do now contain the payload of the
message response in their payload.
* MessageHeaders are now part of the headers of the acknowledgement
This was done to fix a bug where a response could not get deserialized when it was negatively acknowledged by an exception in ditto (see: https://github.com/eclipse/ditto/pull/959)
=> Adapt extracting of Live-Response from acknowledgement

javascript/lib/api/src/model/things.model.ts, javascript/lib/api/src/options/filter.options.ts, javascript/lib/api/tests/options/filter.options.spec.ts, javascript/lib/api/tests/options/request.options.spec.ts
This PR changes the way number and boolean values are "serialized" in filters. Previously, all values were put in quotation marks (""), but that leads to ditto parsing them wrong. 
Note that objecst might still be serialized as `[Object object]`, but as of my experiments it seems that ditto does not support filtering with a complex object anyways, so I see no value in adding a special case for this.
closes #123
=> Fix serialization of booleans and numbers in filters

javascript/lib/api/src/options/request.options.ts, javascript/lib/api/tests/options/request.options.spec.ts
Fixes #157, which was caused by encoding the sort options twice for search requests.
=> Fix encoding of search options, which did encode the sorting option twice

java/src/main/java/org/eclipse/ditto/client/configuration/AccessTokenAuthenticationConfiguration.java, java/src/main/java/org/eclipse/ditto/client/configuration/ClientCredentialsAuthenticationConfiguration.java, java/src/main/java/org/eclipse/ditto/client/configuration/DisconnectedContext.java, java/src/main/java/org/eclipse/ditto/client/configuration/MessagingConfiguration.java, java/src/main/java/org/eclipse/ditto/client/configuration/TokenAuthenticationConfiguration.java, java/src/main/java/org/eclipse/ditto/client/configuration/WebSocketMessagingConfiguration.java, java/src/main/java/org/eclipse/ditto/client/internal/DefaultDittoClient.java, java/src/main/java/org/eclipse/ditto/client/internal/OutgoingMessageFactory.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/AdaptableBus.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/BusFactory.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/Classification.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/Classifiers.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/DefaultAdaptableBus.java, java/src/main/java/org/eclipse/ditto/client/internal/bus/DefaultPointerBus.java, java/src/main/java/org/eclipse/ditto/client/live/internal/LiveImpl.java, java/src/main/java/org/eclipse/ditto/client/messaging/MessagingProvider.java, java/src/main/java/org/eclipse/ditto/client/messaging/MessagingProviders.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/AbstractTokenAuthenticationProvider.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/AccessTokenAuthenticationProvider.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/ClientCredentialsAuthenticationProvider.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/DefaultDisconnectedContext.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/Retry.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/ChangeUpwardsDownwardsPropagationTest.java, java/src/test/java/org/eclipse/ditto/client/configuration/internal/ClientCredentialsAuthenticationConfigurationTest.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/ClientCredentialsJsonWebTokenSupplierTest.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/MockMessagingProvider.java, java/src/test/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProviderTest.java
* called whenever the connection to the Ditto backend was disconnected
* provides a context of who initiated the disconnection + an optional cause
* provides means to e.g. close the client as a result or to perform a reconnect
in addition: fixed executor service creation in Ditto: by default a ScheduledExecutorService with a high "corePoolSize" was configured as default
* only use "scheduled" exector for schedluded tasks
* provide Ditto client sessionId for thread factories (to append in thread names)
* make it possible to configure user code provided "scheduled" executor
=> Enhance Ditto java client with a "disconnection listener"

java/src/main/java/org/eclipse/ditto/client/internal/VersionReader.java, java/src/main/java/org/eclipse/ditto/client/messaging/MessagingProviders.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java
* known bug for Java 8: https://bugs.openjdk.java.net/browse/JDK-8129861
* use corePoolSize 0 for a Java Runtime > 8
=> fixed that for Java Runtime 8, using corePoolSize 0 leads to CPU usage  of 100%

java/src/main/java/org/eclipse/ditto/client/internal/OptionsToDittoHeaders.java, java/src/main/java/org/eclipse/ditto/client/internal/OutgoingMessageFactory.java, java/src/main/java/org/eclipse/ditto/client/management/CommonManagement.java, java/src/main/java/org/eclipse/ditto/client/management/FeatureDefinitionManagement.java, java/src/main/java/org/eclipse/ditto/client/management/FeatureHandle.java, java/src/main/java/org/eclipse/ditto/client/management/FeaturePropertiesManagement.java, java/src/main/java/org/eclipse/ditto/client/management/ThingAttributeManagement.java, java/src/main/java/org/eclipse/ditto/client/management/ThingHandle.java, java/src/main/java/org/eclipse/ditto/client/options/OptionName.java, java/src/main/java/org/eclipse/ditto/client/options/Options.java, java/src/main/java/org/eclipse/ditto/client/options/internal/LiveChannelConditionOptionVisitor.java, java/src/main/java/org/eclipse/ditto/client/options/internal/OptionsEvaluator.java, java/src/test/java/org/eclipse/ditto/client/internal/OptionsToDittoHeadersTest.java, java/src/test/java/org/eclipse/ditto/client/internal/OutgoingMessageFactoryTest.java, java/src/test/java/org/eclipse/ditto/client/options/OptionsTest.java, java/src/test/java/org/eclipse/ditto/client/options/internal/GlobalOptionsEvaluatorTest.java, java/src/test/java/org/eclipse/ditto/client/options/internal/LiveChannelConditionOptionVisitorTest.java
See [Ditto issue #1228](https://github.com/eclipse/ditto/issues/1228) to learn about the smart channel strategy feature.
Also added some missing Javadoc comments for possibly thrown exceptions.
Signed-off-by: Juergen Fickel <juergen.fickel@bosch.io>
=> Added option for live channel condition.

java/src/main/java/org/eclipse/ditto/client/DittoClient.java, java/src/main/java/org/eclipse/ditto/client/configuration/MessagingConfiguration.java, java/src/main/java/org/eclipse/ditto/client/internal/AbstractHandle.java, java/src/main/java/org/eclipse/ditto/client/internal/CommonManagementImpl.java, java/src/main/java/org/eclipse/ditto/client/internal/DefaultDittoClient.java, java/src/main/java/org/eclipse/ditto/client/live/LiveCommandProcessor.java, java/src/main/java/org/eclipse/ditto/client/live/commands/LiveCommandHandler.java, java/src/main/java/org/eclipse/ditto/client/live/events/EventEmitter.java, java/src/main/java/org/eclipse/ditto/client/live/internal/LiveImpl.java, java/src/main/java/org/eclipse/ditto/client/live/messages/MessageSender.java, java/src/main/java/org/eclipse/ditto/client/management/ClientReconnectingException.java, java/src/main/java/org/eclipse/ditto/client/management/CommonManagement.java, java/src/main/java/org/eclipse/ditto/client/management/FeatureHandle.java, java/src/main/java/org/eclipse/ditto/client/management/ThingHandle.java, java/src/main/java/org/eclipse/ditto/client/messaging/MessagingProvider.java, java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java, java/src/main/java/org/eclipse/ditto/client/policies/Policies.java, java/src/main/java/org/eclipse/ditto/client/twin/Twin.java, java/src/main/java/org/eclipse/ditto/client/twin/internal/TwinImpl.java
Prior the sender of a message only got clues about dropped messages due to reconnect in the clients logs, but couldn't handle this case in code.
The ClientReconnectingException can be handled by the sender and an optional buffering/ retrying strategy can be implemented.
In methods returning a CompletionStage the stage will complete exceptionally conatining the error, in other methods the exception is thrown and has to be catched for custom handling.
=> Adds a ClientReconnectingException which is thrown if the client is attempting a reconnect while a message should be sent.

javascript/lib/api/src/model/response.ts, javascript/lib/api/src/options/request.options.ts, javascript/lib/api/tests/options/request.options.spec.ts
As per the documentation (https://www.eclipse.org/ditto/basic-search.html#rql-paging-deprecated), pagination via the `limit` parameter is deprecated and might get removed in the future.
This PR adds support for cursor pagination to the JS client so applications using the client can use the new pagination style
=> [JS] Add support for cursor pagination to JS clients

javascript/lib/api/src/client/handles/messages-http.ts, javascript/lib/api/src/client/handles/search.ts, javascript/lib/api/src/client/request-factory/http-request-sender.ts, javascript/lib/api/src/client/request-factory/request-sender.ts, javascript/lib/api/src/client/request-factory/websocket-request-sender.ts, javascript/lib/api/tests/client/http/search.http.spec.ts
Added JavaScript support for https://github.com/eclipse-ditto/ditto/pull/1706
=> Search and count by post

javascript/lib/api/src/client/constants/content-type.ts, javascript/lib/api/src/client/handles/search.ts, javascript/lib/api/tests/client/http/http.helper.ts, javascript/lib/api/tests/client/http/search.http.spec.ts
Content-Type was not set correctly for postCount() and postSearch()
=> fix: set correct Content-Type

java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java
- since the connectExecutor thread starts a reconnect which in turn causes the websocket connection to go into onConnected() method in the default(callback). This can cause an emit of message before reconnecting boolean is set to false
- introduced a mechanism in order to make sure and retry several times to get the correct value
Fixes: #231
=> re-check reconnecting state before emitting
