eclipse-ditto/ditto-clients

java/src/main/java/org/eclipse/ditto/client/DittoClient.java
java/src/main/java/org/eclipse/ditto/client/internal/DittoClientImpl.java
java/src/main/java/org/eclipse/ditto/client/messaging/MessagingProvider.java
java/src/main/java/org/eclipse/ditto/client/messaging/websocket/internal/WsMessagingProvider.java
java/src/test/java/org/eclipse/ditto/client/DittoClientUsageExamples.java
java/src/test/java/org/eclipse/ditto/client/messaging/mock/MockMessagingProvider.java

adds a method `sendDittoProtocol(Adaptable)` to the `DittoClient` interface

allow to directly send DittoProtocol Adaptables via the DittoClient

---

java/src/main/java/org/eclipse/ditto/client/internal/bus/DefaultRegistry.java
java/src/test/java/org/eclipse/ditto/client/internal/bus/DefaultJsonPointerSelectorTest.java
java/src/test/java/org/eclipse/ditto/client/internal/bus/DefaultRegistryTest.java

[Java] Fix that only one consumer got changes

---

java/pom.xml

Signed-off-by: krj1imb <johannes.schneider@bosch-si.com>

added profiles to build a release

---

javascript/lerna.json
javascript/lib/api/package-lock.json
javascript/lib/api/package.json
javascript/lib/dom/package-lock.json
javascript/lib/dom/package.json
javascript/lib/dom/rollup.config.js
javascript/lib/node/package-lock.json
javascript/lib/node/package.json
javascript/package-lock.json
javascript/package.json

Signed-off-by: Florian Fendt <Florian.Fendt@bosch-si.com>

[js] fix rollup configuration and prepare release 1.0.0-pre2

---

java/pom.xml

Signed-off-by: Michael Gantert <michael.gantert@bosch.io>

JaCoCo: Switch from binary (deprecated) to xml report.

---

java/src/main/java/org/eclipse/ditto/client/configuration/WebSocketMessagingConfiguration.java

The ws path suffix was always appended to the baseUri even if the ws path was already appended.

Append ws path only if needed

---

java/src/main/java/org/eclipse/ditto/client/messaging/internal/Retry.java
java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java
java/src/test/java/org/eclipse/ditto/client/messaging/internal/RetryTest.java

Signed-off-by: Yannic Klem <yannic.klem@bosch.io>

Minor code improvements

---

java/src/main/java/org/eclipse/ditto/client/live/events/internal/ImmutableGlobalEventFactory.java

Fixed in PR https://github.com/eclipse/ditto/pull/825
Successful compilation will work after the Ditto PR was merged

adjusted Ditto Event API usage to Ditto metadata bugfix

---

java/README.md
java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java
java/src/test/java/org/eclipse/ditto/client/internal/ClientShutdownTest.java
java/src/test/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProviderTest.java

Tested in WebSocketMessagingProviderTest.

Notify error handler on initial connection error if initial reconnection is deactivated.

---

javascript/lib/node/src/node-http.ts
javascript/lib/node/src/node-websocket.ts
legal/NOTICE.md

Fixes bug where node http client where connecting using the proxy agent, even if it was not set.
Fixes: #93 
Signed-off-by: tobias <tobias@zept.io>

Check proxyAgent.options.path

---

java/src/main/java/org/eclipse/ditto/client/internal/DefaultDittoClient.java

Adds the possibility to receive events for desired properties modifications.
Part of ditto issue eclipse/ditto#697

Add events for desired properties to ThingChange

---

java/src/test/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProviderTest.java

Signed-off-by: Dominik Guggemos <dominik.guggemos@bosch.io>

Ignore flappy unit test until fixed

---

.github/workflows/license-check.yml
.github/workflows/maven.yml
.github/workflows/nodejs.yml

for added files is the current year

added commit hook for checking that license header's year

---

.github/workflows/license-check.yml
java/pom.xml
java/src/main/java/org/eclipse/ditto/client/ack/internal/ImmutableAcknowledgementRequestHandle.java
java/src/main/java/org/eclipse/ditto/client/changes/AcknowledgementRequestHandle.java
java/src/main/java/org/eclipse/ditto/client/internal/AbstractHandle.java
java/src/main/java/org/eclipse/ditto/client/internal/CommonManagementImpl.java
java/src/main/java/org/eclipse/ditto/client/live/internal/LiveMessagesUtil.java
java/src/main/java/org/eclipse/ditto/client/live/messages/MessageSender.java
java/src/main/java/org/eclipse/ditto/client/live/messages/internal/ImmutableDeserializingMessage.java
java/src/main/java/org/eclipse/ditto/client/live/messages/internal/ImmutableMessageSender.java
java/src/main/java/org/eclipse/ditto/client/live/messages/internal/ImmutableRepliableMessage.java
java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java
java/src/test/java/org/eclipse/ditto/client/DittoClientFeaturesTest.java
java/src/test/java/org/eclipse/ditto/client/DittoClientLiveTest.java
java/src/test/java/org/eclipse/ditto/client/DittoClientTest.java
java/src/test/java/org/eclipse/ditto/client/DittoClientThingTest.java
java/src/test/java/org/eclipse/ditto/client/DittoClientTwinTest.java
java/src/test/java/org/eclipse/ditto/client/DittoClientUsageExamples.java
java/src/test/java/org/eclipse/ditto/client/assertions/ThingErrorResponseAssert.java
legal/headers/license-header-2020.txt

Signed-off-by: Juergen Fickel <juergen.fickel@bosch.io>

Ditto issue #921: Deprecated HttpStatusCode and replaced it with HttpStatus

---

javascript/lib/api/src/client/handles/features.interfaces.ts
javascript/lib/api/src/client/handles/features.ts
javascript/lib/api/src/client/handles/policies.ts
javascript/lib/api/src/client/handles/things.interfaces.ts
javascript/lib/api/src/client/handles/things.ts
javascript/lib/api/src/client/request-factory/request-sender.ts
javascript/lib/api/src/model/response.ts
javascript/lib/api/tests/client/http/features.http.spec.ts
javascript/lib/api/tests/client/http/http-requester.mock.ts
javascript/lib/api/tests/client/http/policies.http.spec.ts
javascript/lib/api/tests/client/http/things.http.spec.ts
legal/NOTICE.md

fix PUT request for existing thing

---

javascript/lib/api/src/client/handles/things.interfaces.ts
javascript/lib/api/src/client/handles/things.ts
javascript/lib/api/src/model/things.model.ts
javascript/lib/api/tests/client/http/things.http.spec.ts
javascript/lib/api/tests/model/things.model.spec.ts

Adds a `_definition` field to the thing model.
Fixes #127

expose thing definition

---

javascript/lib/api/package.json
javascript/lib/dom/package.json
javascript/lib/node/package.json
javascript/package.json

* use SPDX identifier: "EPL-2.0"

fixed license declaration of Ditto JavaScript client in package.json files

---

java/pom.xml
legal/NOTICE.md

consolidated dependencies by using same dependency versions as in Ditto
* updated used websocket library to latest bugfix

Improve/consolidate Maven dependency management

---

java/pom.xml
java/src/main/assembly/assembly.xml
java/src/test/java/org/eclipse/ditto/client/RunOSGiContainerIntegrationTest.java

after having added new "announcements" modules to Ditto signals

fix OSGi test / imports

---

javascript/lib/api/package-lock.json
javascript/lib/dom/package-lock.json
javascript/lib/node/package-lock.json
javascript/lib/node/package.json
javascript/package-lock.json
javascript/package.json

Signed-off-by: Florian Fendt <Florian.Fendt@bosch.io>

Update JS client dependencies

---

java/src/main/java/org/eclipse/ditto/client/messaging/internal/DummyAuthenticationProvider.java
javascript/lib/api/src/auth/auth-provider.ts
javascript/lib/dom/src/dom-auth.ts
javascript/lib/dom/tests/dom-auth.spec.ts

See eclipse/ditto#667.
Fixes: #29 
Signed-off-by: Dominik Guggemos <dominik.guggemos@bosch.io>

add websocket auth provider for dom environments

---

java/src/main/assembly/assembly.xml
java/src/test/java/org/eclipse/ditto/client/RunOSGiContainerIntegrationTest.java

... by adding ditto-connectivity-model into bundles assembly

Fix RunOSGiContainerIntegrationTest

---

java/src/main/java/org/eclipse/ditto/client/messaging/internal/WebSocketMessagingProvider.java

add reconnecting behavior when an unintentional disconnect occures 
(this can happen when the gateway or nginx container get killed);

Improve reconnect behavior for unintentional disconnects

---

java/src/main/java/org/eclipse/ditto/client/internal/HandlerRegistry.java
java/src/main/java/org/eclipse/ditto/client/live/internal/LiveFeatureHandleImpl.java
java/src/main/java/org/eclipse/ditto/client/live/internal/LiveImpl.java
java/src/main/java/org/eclipse/ditto/client/live/internal/LiveMessagesUtil.java
java/src/main/java/org/eclipse/ditto/client/live/internal/LiveThingHandleImpl.java

This PR fixes an incorrect variable replacement in the featureSelector in LiveThingHandleImpl.

Fix incorrect variable replacement for messageSubject in featureSelector

---

java/src/test/java/org/eclipse/ditto/client/RunOSGiContainerIntegrationTest.java

Test will only run successful after https://github.com/eclipse/ditto/pull/1112 was merged.

enhanced OSGi test for instantiating classes relying on ClassIndex import

---

java/pom.xml
legal/3rd-party-dependencies/compile.txt
legal/3rd-party-dependencies/maven-plugins.txt
legal/3rd-party-dependencies/test.txt
legal/NOTICE-THIRD-PARTY.md

* classindex, slf4j, logback, junit

Update several Java Client dependencies

---

javascript/lib/api/src/client/handles/events.ts
javascript/lib/api/src/client/request-factory/websocket-request-handler.ts
javascript/lib/api/src/model/ditto-protocol.ts
javascript/lib/api/tests/client/websocket/commands.websocket.spec.ts
javascript/lib/api/tests/client/websocket/events.websocket.spec.ts
javascript/lib/api/tests/client/websocket/messages.websocket.spec.ts
javascript/package-lock.json

[#193] fixed responding to messages in JS client did not preserve the message "headers"

---

javascript/lib/api/src/model/model.ts

Fixes #202 
Signed-off-by: Dirk Van Haerenborgh <dirk.vanhaerenborgh@aloxy.io>

Declare id field as abstract

---

java/pom.xml

This is to support build with jdk17.

Increased maven-bundle-plugin version
